name: CI
on: [push, pull_request]

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # If requirements.txt exists, install it; otherwise skip.
      - name: Install deps (if any)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping installs."
          fi

      - name: Sanity print
        run: python -c "print('CI sanity check ✅')"
